apiVersion: v1
kind: Service
metadata: 
  name: svc-cluster-1
spec: 
  type: ClusterIP # Optional as it is the default
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: public-app